// Typelizer digest 4b2c9b646849157b708925a318140004
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /manifest */
  manifest: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/manifest', {}, options),
    method: 'get',
  }),
}
