// Typelizer digest 4ae6d26bbe31f228b0b8204678753ea2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Certification = {
  id: number;
  profile_id: number;
  name: string;
  issuer: string;
  description: string | null;
  credential_url: string | null;
  credential_id: string | null;
  issued_at: string | null;
  expires_at: string | null;
  position: number;
  created_at: string;
  updated_at: string;
}

export type { Certification };
