// Typelizer digest ce2d2242983ef9789e4f1450b0ce740a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Education = {
  id: number;
  profile_id: number;
  institution: string;
  course: string;
  degree: string | null;
  description: string | null;
  start_date: string;
  end_date: string | null;
  current: boolean;
  position: number;
  created_at: string;
  updated_at: string;
}

export type { Education };
