// Typelizer digest 8c84e310204bd1ecdcf5afb809a58595
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Experience = {
  id: number;
  profile_id: number;
  company: string;
  role: string;
  employment_type: string | null;
  location: string | null;
  description: string | null;
  start_date: string;
  end_date: string | null;
  current: boolean;
  position: number;
  created_at: string;
  updated_at: string;
}

export type { Experience };
