// Typelizer digest aae162938caf2bef8eb0f82e1c175fd3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile} from '@/types'

type HomeIndex = {
  profile: Profile;
}

export type { HomeIndex };
