// Typelizer digest 7650ebf9485565ef392dd24626bbb7a7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Experience, Education, Skill, Project, Certification, SocialLink} from '@/types'

type Profile = {
  id: number;
  name: string;
  headline: string | null;
  bio: string | null;
  location: string | null;
  email: string | null;
  phone: string | null;
  github_url: string | null;
  linkedin_url: string | null;
  website_url: string | null;
  avatar_url: string | null;
  resume_url: string | null;
  available_for_work: boolean;
  created_at: string;
  updated_at: string;
  experiences: Array<Experience>;
  educations: Array<Education>;
  skills: Array<Skill>;
  projects: Array<Project>;
  certifications: Array<Certification>;
  social_links: Array<SocialLink>;
}

export type { Profile };
