// Typelizer digest a254717b91c99025f061713435c41fac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Skill} from '@/types'

type Project = {
  id: number;
  profile_id: number;
  name: string;
  slug: string;
  short_description: string | null;
  description: string | null;
  image_url: string | null;
  github_url: string | null;
  demo_url: string | null;
  featured: boolean;
  position: number;
  start_date: string | null;
  end_date: string | null;
  created_at: string;
  updated_at: string;
  skills: Array<Skill>;
}

export type { Project };
