// Typelizer digest d7d671189df05303b812629145fe4af3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Skill} from '@/types'

type ProjectSkill = {
  id: number;
  project_id: number;
  skill_id: number;
  created_at: string;
  updated_at: string;
  skill: Skill;
}

export type { ProjectSkill };
