// Typelizer digest 174271113926836b928d459a6f28ede3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile, Project} from '@/types'

type ProjectShow = {
  profile: Profile;
  project: Project;
  previous_slug: unknown;
  next_slug: unknown;
}

export type { ProjectShow };
