// Typelizer digest 6646821ac0ae1fff6e642e1c9101e069
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  id: number;
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
}

export type { Session };
