// Typelizer digest dd9ac83b382da36caba68b154b61a901
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Session} from '@/types'

type SettingsSessionsIndex = {
  sessions: Array<Session>;
}

export type { SettingsSessionsIndex };
