// Typelizer digest 9d6a3ed84ad2afad8f44e57e66de8684
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
}

export type { SharedProps };
