// Typelizer digest 1cbe60ab01a5ba87c41b6ab7f161962c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Skill = {
  id: number;
  profile_id: number;
  name: string;
  slug: string;
  category: string;
  icon: string;
  description: string | null;
  level: string | null;
  position: number;
  created_at: string;
  updated_at: string;
}

export type { Skill };
