// Typelizer digest 366c64052cb24cdb0d0eac642861675a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SocialLink = {
  id: number;
  profile_id: number;
  platform: string;
  url: string;
  username: string | null;
  icon: string | null;
  position: number;
  created_at: string;
  updated_at: string;
}

export type { SocialLink };
