// Typelizer digest 7b8df1ccd4254fa21a0e1381358dc604
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
  avatar?: string;
}

export type { User };
