// Typelizer digest fdc302cea7003f16efe98393b1d6e6eb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Session} from '@/types'

type Auth = {
  user: User;
  session: Session;
}

export type { Auth };
