// Typelizer digest 6434091a85de6ca512809ddbf2973b25
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type IdentityPasswordResetsEdit = {
  email: string;
  sid?: string;
}

export type { IdentityPasswordResetsEdit };
