// Typelizer digest 2e2399693e3016e69544a6efff5ca30e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /contacts */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/contacts', {}, options),
    method: 'post',
  }),
}
