// Typelizer digest b3ba22883cf61d4e57e4d89f8bb5217c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as home } from './HomeController'
export { default as locales } from './LocalesController'

import _home from './HomeController'
import _locales from './LocalesController'

export const root = _home.index
export const switchLocale = _locales.update
