// Typelizer digest 8a90d3f6fbdf899423b5d4d5052ba578
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as contacts } from './ContactsController'
export { default as home } from './HomeController'
export { default as locales } from './LocalesController'
export { default as projects } from './ProjectsController'
export { default as railsPwa } from './Rails/PwaController'
export { default as sitemaps } from './SitemapsController'
export { default as themes } from './ThemesController'

import _projects from './ProjectsController'
import _railsPwa from './Rails/PwaController'
import _home from './HomeController'
import _sitemaps from './SitemapsController'
import _locales from './LocalesController'
import _themes from './ThemesController'

export const project = _projects.show
export const pwaManifest = _railsPwa.manifest
export const root = _home.index
export const sitemap = _sitemaps.show
export const switchLocale = _locales.update
export const switchTheme = _themes.update
