// Typelizer digest af180c48107b5ccff1c87ebe82fa70b0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /locale */
  update: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/locale', {}, options),
    method: 'get',
  }),
}
