// Typelizer digest b152346a9a722ff0346ba4611688dd49
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /projects/:slug */
  show: (
    params: { slug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/projects/:slug', params, options),
    method: 'get',
  }),
}
