// Typelizer digest 4d4ebd36531118982950632dd53e11da
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sitemap */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/sitemap', {}, options),
    method: 'get',
  }),
}
