// Typelizer digest d169aa799787d210ab6ce19706fafd66
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /theme */
  update: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/theme', {}, options),
    method: 'get',
  }),
}
